version: '3.5'

services:
  db_auth:
    container_name: 'db_adc'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=Edro9802!
      - POSTGRES_USER=edro
    image: postgres:15.1-alpine
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
